//! Build script that generates postgres migration list at compile time.
//!
//! This eliminates the need to manually register migrations in migrations.rs.

use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    generate_postgres_migrations();
}

fn generate_postgres_migrations() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("postgres_migrations.rs");

    let migrations_dir = Path::new(&manifest_dir).join("migrations/postgres");

    // Collect migration directories
    let mut migrations: Vec<(String, String)> = Vec::new();

    if migrations_dir.exists() {
        let mut entries: Vec<_> = fs::read_dir(&migrations_dir)
            .expect("Failed to read migrations/postgres directory")
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_dir())
            .collect();

        // Sort by directory name (which starts with timestamp)
        entries.sort_by_key(|e| e.file_name());

        for entry in entries {
            let dir_name = entry.file_name().to_string_lossy().to_string();

            // Extract version from directory name (e.g., "2025-01-01-200000" from "2025-01-01-200000_archive_history")
            let version = dir_name.split('_').next().unwrap_or(&dir_name).to_string();

            let up_sql_path = entry.path().join("up.sql");
            if up_sql_path.exists() {
                // Use absolute path from CARGO_MANIFEST_DIR
                // Replace backslashes with forward slashes for Windows compatibility
                let absolute_path =
                    format!("{}/migrations/postgres/{}/up.sql", manifest_dir, dir_name)
                        .replace('\\', "/");
                migrations.push((version, absolute_path));
            }
        }
    }

    // Generate the Rust code
    let mut output = String::new();
    output.push_str("// Auto-generated by build.rs - do not edit manually\n\n");
    output.push_str("#[cfg(feature = \"postgres\")]\n");
    output.push_str("pub static POSTGRES_MIGRATIONS: &[(&str, &str)] = &[\n");

    for (version, path) in &migrations {
        output.push_str(&format!(
            "    (\"{}\", include_str!(\"{}\")),\n",
            version, path
        ));
    }

    output.push_str("];\n");

    let mut file = fs::File::create(&dest_path).expect("Failed to create postgres_migrations.rs");
    file.write_all(output.as_bytes())
        .expect("Failed to write postgres_migrations.rs");

    // Tell cargo to rerun if migrations change
    println!("cargo:rerun-if-changed=migrations/postgres");
}
